import { Player, Match, Team, Training, FinanceRecord } from '@/types';
import { getRoles } from './player';

const createAttributes = (attrs: Partial<Player['attributes']>): Player['attributes'] => ({
  strength: 0.5,
  acceleration: 0.5,
  topSpeed: 0.5,
  dribbleSpeed: 0.5,
  jump: 0.5,
  tackling: 0.5,
  ballKeeping: 0.5,
  passing: 0.5,
  longBall: 0.5,
  agility: 0.5,
  shooting: 0.5,
  shootPower: 0.5,
  positioning: 0.5,
  reaction: 0.5,
  ballControl: 0.5,
  ...attrs,
});

const defaultPhysical = { height: 180, weight: 75 };
const defaultVitals = { health: 1, condition: 0.82, motivation: 0.78, injuryStatus: 'healthy' as const };

const rawMockPlayers: Omit<Player, 'potential'>[] = [
  {
    id: '1',
    name: 'Mehmet Özkan',
    position: 'GK',
    roles: getRoles('GK'),
    overall: 0.852,
    attributes: createAttributes({
      topSpeed: 0.432,
      acceleration: 0.5,
      agility: 0.5,
      shooting: 0.123,
      passing: 0.765,
      tackling: 0.891,
      ballControl: 0.234,
      strength: 0.789,
    }),
    age: 28,
    squadRole: 'starting',
    ...defaultPhysical,
    ...defaultVitals,
  },
  {
    id: '2',
    name: 'Ali Yılmaz',
    position: 'CB',
    roles: getRoles('CB'),
    overall: 0.789,
    attributes: createAttributes({
      topSpeed: 0.567,
      acceleration: 0.5,
      agility: 0.5,
      shooting: 0.234,
      passing: 0.678,
      tackling: 0.912,
      ballControl: 0.345,
      strength: 0.823,
    }),
    age: 26,
    squadRole: 'starting',
    ...defaultPhysical,
    ...defaultVitals,
  },
  {
    id: '3',
    name: 'Can Demir',
    position: 'CB',
    roles: getRoles('CB'),
    overall: 0.776,
    attributes: createAttributes({
      topSpeed: 0.534,
      acceleration: 0.5,
      agility: 0.5,
      shooting: 0.267,
      passing: 0.689,
      tackling: 0.898,
      ballControl: 0.312,
      strength: 0.834,
    }),
    age: 24,
    squadRole: 'starting',
    ...defaultPhysical,
    ...defaultVitals,
  },
  {
    id: '4',
    name: 'Emre Kara',
    position: 'LB',
    roles: getRoles('LB'),
    overall: 0.723,
    attributes: createAttributes({
      topSpeed: 0.789,
      acceleration: 0.5,
      agility: 0.5,
      shooting: 0.345,
      passing: 0.712,
      tackling: 0.678,
      ballControl: 0.567,
      strength: 0.654,
    }),
    age: 25,
    squadRole: 'starting',
    ...defaultPhysical,
    ...defaultVitals,
  },
  {
    id: '5',
    name: 'Burak Şen',
    position: 'RB',
    roles: getRoles('RB'),
    overall: 0.734,
    attributes: createAttributes({
      topSpeed: 0.798,
      acceleration: 0.5,
      agility: 0.5,
      shooting: 0.356,
      passing: 0.723,
      tackling: 0.689,
      ballControl: 0.578,
      strength: 0.665,
    }),
    age: 27,
    squadRole: 'starting',
    ...defaultPhysical,
    ...defaultVitals,
  },
  {
    id: '6',
    name: 'Oğuz Çelik',
    position: 'CM',
    roles: getRoles('CM'),
    overall: 0.812,
    attributes: createAttributes({
      topSpeed: 0.656,
      acceleration: 0.5,
      agility: 0.5,
      shooting: 0.534,
      passing: 0.887,
      tackling: 0.567,
      ballControl: 0.723,
      strength: 0.678,
    }),
    age: 24,
    squadRole: 'starting',
    ...defaultPhysical,
    ...defaultVitals,
  },
  {
    id: '7',
    name: 'Serkan Aydın',
    position: 'CM',
    roles: getRoles('CM'),
    overall: 0.798,
    attributes: createAttributes({
      topSpeed: 0.645,
      acceleration: 0.5,
      agility: 0.5,
      shooting: 0.523,
      passing: 0.876,
      tackling: 0.556,
      ballControl: 0.712,
      strength: 0.667,
    }),
    age: 26,
    squadRole: 'starting',
    ...defaultPhysical,
    ...defaultVitals,
  },
  {
    id: '8',
    name: 'Kemal Arslan',
    position: 'LW',
    roles: getRoles('LW'),
    overall: 0.845,
    attributes: createAttributes({
      topSpeed: 0.923,
      acceleration: 0.5,
      agility: 0.5,
      shooting: 0.678,
      passing: 0.734,
      tackling: 0.234,
      ballControl: 0.889,
      strength: 0.567,
    }),
    age: 23,
    squadRole: 'starting',
    ...defaultPhysical,
    ...defaultVitals,
  },
  {
    id: '9',
    name: 'Hakan Polat',
    position: 'RW',
    roles: getRoles('RW'),
    overall: 0.834,
    attributes: createAttributes({
      topSpeed: 0.912,
      acceleration: 0.5,
      agility: 0.5,
      shooting: 0.667,
      passing: 0.723,
      tackling: 0.223,
      ballControl: 0.878,
      strength: 0.556,
    }),
    age: 25,
    squadRole: 'starting',
    ...defaultPhysical,
    ...defaultVitals,
  },
  {
    id: '10',
    name: 'Murat Koç',
    position: 'CAM',
    roles: getRoles('CAM'),
    overall: 0.867,
    attributes: createAttributes({
      topSpeed: 0.734,
      acceleration: 0.5,
      agility: 0.5,
      shooting: 0.789,
      passing: 0.923,
      tackling: 0.345,
      ballControl: 0.845,
      strength: 0.623,
    }),
    age: 27,
    squadRole: 'starting',
    ...defaultPhysical,
    ...defaultVitals,
  },
  {
    id: '11',
    name: 'Volkan Tekin',
    position: 'ST',
    roles: getRoles('ST'),
    overall: 0.889,
    attributes: createAttributes({
      topSpeed: 0.823,
      acceleration: 0.5,
      agility: 0.5,
      shooting: 0.945,
      passing: 0.678,
      tackling: 0.234,
      ballControl: 0.787,
      strength: 0.756,
    }),
    age: 29,
    squadRole: 'starting',
    ...defaultPhysical,
    ...defaultVitals,
  },
  {
    id: '12',
    name: 'Yusuf Balık',
    position: 'GK',
    roles: getRoles('GK'),
    overall: 0.678,
    attributes: createAttributes({
      topSpeed: 0.345,
      acceleration: 0.5,
      agility: 0.5,
      shooting: 0.089,
      passing: 0.567,
      tackling: 0.723,
      ballControl: 0.123,
      strength: 0.634,
    }),
    age: 31,
    squadRole: 'bench',
    ...defaultPhysical,
    ...defaultVitals,
  },
  {
    id: '13',
    name: 'Fatih Güven',
    position: 'CB',
    roles: getRoles('CB'),
    overall: 0.634,
    attributes: createAttributes({
      topSpeed: 0.456,
      acceleration: 0.5,
      agility: 0.5,
      shooting: 0.167,
      passing: 0.523,
      tackling: 0.789,
      ballControl: 0.234,
      strength: 0.678,
    }),
    age: 30,
    squadRole: 'bench',
    ...defaultPhysical,
    ...defaultVitals,
  },
  {
    id: '14',
    name: 'Deniz Akın',
    position: 'CM',
    roles: getRoles('CM'),
    overall: 0.687,
    attributes: createAttributes({
      topSpeed: 0.567,
      acceleration: 0.5,
      agility: 0.5,
      shooting: 0.445,
      passing: 0.734,
      tackling: 0.456,
      ballControl: 0.612,
      strength: 0.578,
    }),
    age: 28,
    squadRole: 'bench',
    ...defaultPhysical,
    ...defaultVitals,
  },
];


export const mockPlayers: Player[] = rawMockPlayers.map((p) => ({
  ...p,
  potential: Math.min(1, p.overall + Math.random() * (1 - p.overall)),
}));

export const upcomingMatches: Match[] = [
  {
    id: '1',
    opponent: 'Galatasaray',
    opponentLogo: '🦁',
    opponentLogoUrl: '/Logo/galatasaray.svg',
    date: '2025-08-20',
    time: '20:00',
    venue: 'home',
    status: 'scheduled',
    competition: 'Süper Lig',
    venueName: 'Rams Park',
    opponentStats: {
      overall: 0.912,
      form: ['W', 'W', 'D', 'W', 'W'],
      keyPlayers: [
        {
          name: 'Mauro Icardi',
          position: 'ST',
          highlight: '15 gol',
          stats: { matches: 18, goals: 15, assists: 4, rating: 7.9, minutes: 1520 },
        },
        {
          name: 'Kerem Aktürkoğlu',
          position: 'LW',
          highlight: '11 asist',
          stats: { matches: 20, goals: 6, assists: 11, rating: 7.6, minutes: 1685 },
        },
        {
          name: 'Lucas Torreira',
          position: 'CM',
          highlight: '%90 pas isabeti',
          stats: { matches: 21, goals: 2, assists: 5, rating: 7.4, minutes: 1810 },
        },
        {
          name: 'Dries Mertens',
          position: 'CAM',
          highlight: '8 gol katkısı',
          stats: { matches: 19, goals: 5, assists: 3, rating: 7.2, minutes: 1405 },
        },
        {
          name: 'Barış Alper Yılmaz',
          position: 'RW',
          highlight: '3 kritik gol',
          stats: { matches: 17, goals: 4, assists: 4, rating: 7.1, minutes: 1320 },
        },
        {
          name: 'Davinson Sánchez',
          position: 'CB',
          highlight: '%72 ikili mücadele',
          stats: { matches: 16, goals: 1, assists: 0, rating: 7.3, minutes: 1440, cleanSheets: 9 },
        },
        {
          name: 'Fernando Muslera',
          position: 'GK',
          highlight: '9 clean sheet',
          stats: { matches: 18, goals: 0, assists: 0, rating: 7.5, minutes: 1620, cleanSheets: 9 },
        },
        {
          name: 'Sacha Boey',
          position: 'RB',
          highlight: '7 top çalma',
          stats: { matches: 15, goals: 1, assists: 2, rating: 7.0, minutes: 1280 },
        },
      ],
    },
  },
  {
    id: '2',
    opponent: 'Fenerbahçe',
    opponentLogo: '🐦',
    date: '2025-08-25',
    time: '19:00',
    venue: 'away',
    status: 'scheduled',
    competition: 'Süper Lig',
  },
];

export const leagueTable: Team[] = [
  {
    name: 'Takımım',
    logo: '⚽',
    overall: 0.823,
    form: 'WWDWL',
    position: 3,
    points: 15,
    played: 7,
    won: 4,
    drawn: 3,
    lost: 0,
    goalDifference: 8,
  },
  {
    name: 'Galatasaray',
    logo: '🦁',
    overall: 0.889,
    form: 'WWWWW',
    position: 1,
    points: 21,
    played: 7,
    won: 7,
    drawn: 0,
    lost: 0,
    goalDifference: 15,
  },
  {
    name: 'Fenerbahçe',
    logo: '🐦',
    overall: 0.867,
    form: 'WWWDL',
    position: 2,
    points: 16,
    played: 7,
    won: 5,
    drawn: 1,
    lost: 1,
    goalDifference: 12,
  },
  {
    name: 'Beşiktaş',
    logo: '🦅',
    overall: 0.845,
    form: 'DWWLW',
    position: 4,
    points: 13,
    played: 7,
    won: 4,
    drawn: 1,
    lost: 2,
    goalDifference: 3,
  },
];

export const trainings: Training[] = [
  {
    id: 'strength',
    name: 'Güç Antrenmanı',
    type: 'strength',
    description: 'Fiziksel gücü artırır',
    duration: 5,
  },
  {
    id: 'acceleration',
    name: 'Hızlanma Antrenmanı',
    type: 'acceleration',
    description: 'Hızlanmayı geliştirir',
    duration: 5,
  },
  {
    id: 'topSpeed',
    name: 'Maksimum Hız Antrenmanı',
    type: 'topSpeed',
    description: 'Maksimum hızı artırır',
    duration: 5,
  },
  {
    id: 'dribbleSpeed',
    name: 'Dribling Hızı Antrenmanı',
    type: 'dribbleSpeed',
    description: 'Dribling hızını geliştirir',
    duration: 5,
  },
  {
    id: 'jump',
    name: 'Sıçrama Antrenmanı',
    type: 'jump',
    description: 'Sıçrama yeteneğini geliştirir',
    duration: 5,
  },
  {
    id: 'tackling',
    name: 'Mücadele Antrenmanı',
    type: 'tackling',
    description: 'Mücadele yeteneklerini geliştirir',
    duration: 5,
  },
  {
    id: 'ballKeeping',
    name: 'Top Saklama Antrenmanı',
    type: 'ballKeeping',
    description: 'Top saklama becerisini geliştirir',
    duration: 5,
  },
  {
    id: 'passing',
    name: 'Pas Antrenmanı',
    type: 'passing',
    description: 'Pas doğruluğunu artırır',
    duration: 5,
  },
  {
    id: 'longBall',
    name: 'Uzun Top Antrenmanı',
    type: 'longBall',
    description: 'Uzun top becerisini geliştirir',
    duration: 5,
  },
  {
    id: 'agility',
    name: 'Çeviklik Antrenmanı',
    type: 'agility',
    description: 'Çevikliği artırır',
    duration: 5,
  },
  {
    id: 'shooting',
    name: 'Şut Antrenmanı',
    type: 'shooting',
    description: 'Şut isabetini geliştirir',
    duration: 5,
  },
  {
    id: 'shootPower',
    name: 'Şut Gücü Antrenmanı',
    type: 'shootPower',
    description: 'Şut gücünü artırır',
    duration: 5,
  },
  {
    id: 'positioning',
    name: 'Pozisyon Alma Antrenmanı',
    type: 'positioning',
    description: 'Pozisyon alma becerisini geliştirir',
    duration: 5,
  },
  {
    id: 'reaction',
    name: 'Refleks Antrenmanı',
    type: 'reaction',
    description: 'Refleksleri geliştirir',
    duration: 5,
  },
  {
    id: 'ballControl',
    name: 'Top Kontrolü Antrenmanı',
    type: 'ballControl',
    description: 'Top kontrolünü geliştirir',
    duration: 5,
  },
];

export const financeRecords: FinanceRecord[] = [
  {
    id: '1',
    type: 'income',
    category: 'Maç Geliri',
    amount: 150000,
    date: '2025-08-15',
    description: 'Galatasaray maçı bilet gelirleri',
  },
  {
    id: '2',
    type: 'income',
    category: 'Sponsorluk',
    amount: 500000,
    date: '2025-08-10',
    description: 'Aylık sponsorluk ödemesi',
  },
  {
    id: '3',
    type: 'expense',
    category: 'Maaşlar',
    amount: 800000,
    date: '2025-08-01',
    description: 'Oyuncu ve teknik kadro maaşları',
  },
  {
    id: '4',
    type: 'expense',
    category: 'Antrenman',
    amount: 25000,
    date: '2025-08-12',
    description: 'Antrenman ekipmanları',
  },
];

