import { Player } from '@/types';

export interface FormationPosition {
  position: Player['position'];
  x: number; // percentage from 0 to 100
  y: number; // percentage from 0 to 100
}

export interface Formation {
  name: string;
  positions: FormationPosition[];
}

export const formations: Formation[] = [
  {
    name: '4-4-2',
    positions: [
      { position: 'GK', x: 50, y: 90 },
      { position: 'LB', x: 15, y: 70 },
      { position: 'CB', x: 35, y: 65 },
      { position: 'CB', x: 65, y: 65 },
      { position: 'RB', x: 85, y: 70 },
      { position: 'LM', x: 15, y: 45 },
      { position: 'CM', x: 40, y: 45 },
      { position: 'CM', x: 60, y: 45 },
      { position: 'RM', x: 85, y: 45 },
      { position: 'ST', x: 40, y: 20 },
      { position: 'ST', x: 60, y: 20 },
    ],
  },
  {
    name: '4-3-3',
    positions: [
      { position: 'GK', x: 50, y: 90 },
      { position: 'LB', x: 15, y: 70 },
      { position: 'CB', x: 35, y: 65 },
      { position: 'CB', x: 65, y: 65 },
      { position: 'RB', x: 85, y: 70 },
      { position: 'CM', x: 30, y: 45 },
      { position: 'CM', x: 50, y: 40 },
      { position: 'CM', x: 70, y: 45 },
      { position: 'LW', x: 20, y: 25 },
      { position: 'ST', x: 50, y: 15 },
      { position: 'RW', x: 80, y: 25 },
    ],
  },
  {
    name: '3-5-2',
    positions: [
      { position: 'GK', x: 50, y: 90 },
      { position: 'CB', x: 30, y: 70 },
      { position: 'CB', x: 50, y: 65 },
      { position: 'CB', x: 70, y: 70 },
      { position: 'LM', x: 10, y: 45 },
      { position: 'CM', x: 30, y: 45 },
      { position: 'CAM', x: 50, y: 40 },
      { position: 'CM', x: 70, y: 45 },
      { position: 'RM', x: 90, y: 45 },
      { position: 'ST', x: 40, y: 20 },
      { position: 'ST', x: 60, y: 20 },
    ],
  },
  {
    name: '4-5-1',
    positions: [
      { position: 'GK', x: 50, y: 90 },
      { position: 'LB', x: 15, y: 70 },
      { position: 'CB', x: 35, y: 65 },
      { position: 'CB', x: 65, y: 65 },
      { position: 'RB', x: 85, y: 70 },
      { position: 'LM', x: 15, y: 50 },
      { position: 'CM', x: 35, y: 50 },
      { position: 'CAM', x: 50, y: 45 },
      { position: 'CM', x: 65, y: 50 },
      { position: 'RM', x: 85, y: 50 },
      { position: 'ST', x: 50, y: 20 },
    ],
  },
  {
    name: '4-2-3-1',
    positions: [
      { position: 'GK', x: 50, y: 90 },
      { position: 'LB', x: 15, y: 70 },
      { position: 'CB', x: 35, y: 65 },
      { position: 'CB', x: 65, y: 65 },
      { position: 'RB', x: 85, y: 70 },
      { position: 'CM', x: 40, y: 55 },
      { position: 'CM', x: 60, y: 55 },
      { position: 'LW', x: 20, y: 35 },
      { position: 'CAM', x: 50, y: 35 },
      { position: 'RW', x: 80, y: 35 },
      { position: 'ST', x: 50, y: 20 },
    ],
  },
  {
    name: '5-3-2',
    positions: [
      { position: 'GK', x: 50, y: 90 },
      { position: 'LB', x: 10, y: 70 },
      { position: 'CB', x: 30, y: 65 },
      { position: 'CB', x: 50, y: 60 },
      { position: 'CB', x: 70, y: 65 },
      { position: 'RB', x: 90, y: 70 },
      { position: 'CM', x: 35, y: 45 },
      { position: 'CAM', x: 50, y: 40 },
      { position: 'CM', x: 65, y: 45 },
      { position: 'ST', x: 40, y: 20 },
      { position: 'ST', x: 60, y: 20 },
    ],
  },
  {
    name: '5-4-1',
    positions: [
      { position: 'GK', x: 50, y: 90 },
      { position: 'LB', x: 10, y: 70 },
      { position: 'CB', x: 30, y: 65 },
      { position: 'CB', x: 50, y: 60 },
      { position: 'CB', x: 70, y: 65 },
      { position: 'RB', x: 90, y: 70 },
      { position: 'LM', x: 20, y: 50 },
      { position: 'CM', x: 40, y: 50 },
      { position: 'CM', x: 60, y: 50 },
      { position: 'RM', x: 80, y: 50 },
      { position: 'ST', x: 50, y: 20 },
    ],
  },
  {
    name: '3-4-3',
    positions: [
      { position: 'GK', x: 50, y: 90 },
      { position: 'CB', x: 30, y: 70 },
      { position: 'CB', x: 50, y: 65 },
      { position: 'CB', x: 70, y: 70 },
      { position: 'LM', x: 10, y: 50 },
      { position: 'CM', x: 40, y: 50 },
      { position: 'CM', x: 60, y: 50 },
      { position: 'RM', x: 90, y: 50 },
      { position: 'LW', x: 20, y: 25 },
      { position: 'ST', x: 50, y: 15 },
      { position: 'RW', x: 80, y: 25 },
    ],
  },
  {
    name: '4-1-4-1',
    positions: [
      { position: 'GK', x: 50, y: 90 },
      { position: 'LB', x: 15, y: 70 },
      { position: 'CB', x: 35, y: 65 },
      { position: 'CB', x: 65, y: 65 },
      { position: 'RB', x: 85, y: 70 },
      { position: 'CM', x: 50, y: 55 },
      { position: 'LM', x: 15, y: 40 },
      { position: 'CM', x: 35, y: 40 },
      { position: 'CAM', x: 65, y: 40 },
      { position: 'RM', x: 85, y: 40 },
      { position: 'ST', x: 50, y: 20 },
    ],
  },
  {
    name: '4-4-1-1',
    positions: [
      { position: 'GK', x: 50, y: 90 },
      { position: 'LB', x: 15, y: 70 },
      { position: 'CB', x: 35, y: 65 },
      { position: 'CB', x: 65, y: 65 },
      { position: 'RB', x: 85, y: 70 },
      { position: 'LM', x: 15, y: 50 },
      { position: 'CM', x: 40, y: 50 },
      { position: 'CM', x: 60, y: 50 },
      { position: 'RM', x: 85, y: 50 },
      { position: 'CAM', x: 50, y: 35 },
      { position: 'ST', x: 50, y: 20 },
    ],
  },
  {
    name: '3-4-1-2',
    positions: [
      { position: 'GK', x: 50, y: 90 },
      { position: 'CB', x: 30, y: 70 },
      { position: 'CB', x: 50, y: 65 },
      { position: 'CB', x: 70, y: 70 },
      { position: 'LM', x: 10, y: 50 },
      { position: 'CM', x: 40, y: 50 },
      { position: 'CM', x: 60, y: 50 },
      { position: 'RM', x: 90, y: 50 },
      { position: 'CAM', x: 50, y: 35 },
      { position: 'ST', x: 40, y: 20 },
      { position: 'ST', x: 60, y: 20 },
    ],
  },
  {
    name: '4-3-2-1',
    positions: [
      { position: 'GK', x: 50, y: 90 },
      { position: 'LB', x: 15, y: 70 },
      { position: 'CB', x: 35, y: 65 },
      { position: 'CB', x: 65, y: 65 },
      { position: 'RB', x: 85, y: 70 },
      { position: 'CM', x: 30, y: 55 },
      { position: 'CM', x: 50, y: 60 },
      { position: 'CM', x: 70, y: 55 },
      { position: 'CAM', x: 40, y: 35 },
      { position: 'CAM', x: 60, y: 35 },
      { position: 'ST', x: 50, y: 20 },
    ],
  },
];

