workflows:
  ios-workflow:
    name: iOS App Store Build
    max_build_duration: 60
    environment:
      ios_signing:
        provisioning_profiles:
          - fhs_app_store_profile
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Add and Sync iOS Platform
        script: |
          npx cap add ios
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd ios/App && pod install
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Create export_options.plist
        script: |
          PROFILE_PATH=$(find ~/Library/MobileDevice/Provisioning\ Profiles -name "*.mobileprovision" | head -n 1)
          if [ -z "$PROFILE_PATH" ]; then
            echo "No provisioning profile found!"
            exit 1
          fi
          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c "Print UUID" /dev/stdin <<< $(security cms -D -i "$PROFILE_PATH"))
          echo "Found Profile UUID: $PROFILE_UUID"
          
          cat > export_options.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>com.nerbuss.fhsmanager</key>
                  <string>$PROFILE_UUID</string>
              </dict>
          </dict>
          </plist>
          EOF
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --export-options-plist export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
