ADMOB_APP_ID_ANDROID=ca-app-pub-4528086511982026~7591944006
ADMOB_REWARDED_UNIT_ID_ANDROID=ca-app-pub-4528086511982026/9622544690
# Release build icin gercek native pano ad unit burada tanimlanmali.
ADMOB_NATIVE_OVERLAY_STADIUM_UNIT_ID_ANDROID=
ADMOB_USE_TEST_IDS=false
