name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install deps
        run: pnpm install --frozen-lockfile=false

      - name: Unit tests (vitest)
        run: pnpm run test:ci

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: E2E (Playwright)
        run: pnpm run test:e2e

